openapi: 3.0.1

info:
    title: Movies API
    version: v0.0.1
    contact:
        name: Marcos Melo
        email: marcos@marcosmelo.tech
    description: This API allows for the creation and querying of movies

servers:
    - url: https://movies-ts-api.heroku.com
      description: Hosted in Heroku, it goes to sleep once every 30 minutes when not used

tags:
    - name: movies

paths:
    /movies:
        get:
            summary: Find all movies
            description: Return all movies
            responses:
                200:
                    description: successfull operation
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Movie'

components:
    schemas:
        Movie:
            type: object
            properties:
                title:
                    type: string
                    example: 'Justice League'
                overview:
                    type: string
                    example: 'A DC Movie'
                releaseDate:
                    type: number
                    example: 2018
                rate:
                    type: number
                    example: 7
                poster:
                    type: string
                    example: 'https://www.movie.com/justice.jpg'
